name: receita_ws
description: Uma biblioteca para consulta de CNPJ para desenvolvedores Dart (Console, Web e Flutter).
version: 1.0.0
homepage: https://receitaws.com.br/
repository: https://github.com/mateuspenha/receita_ws
issue_tracker: https://github.com/mateuspenha/receita_ws/issues
author: Mateus Penha <mateuspenha@gmail.com>

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  http: ^1.1.0
  xml2json: ^6.2.1

dev_dependencies:
  mews_pedantic: ^0.20.0
  test: ^1.24.9